# Generated by Django 3.1 on 2021-06-15 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210615_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='tittle',
        ),
    ]
