# Generated by Django 3.1 on 2021-06-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210617_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_image',
        ),
    ]
