# Generated by Django 3.1 on 2021-06-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_product_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='system_requiremenrs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
